install: npm install
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: "${TRAVIS_BUILD_DIR}/dist"
  on:
    branch: master
  target_branch: gh-pages
after_deploy:
- node tools/run-site-image-maker-ci-build.js
env:
  global:
   - secure: dqR1/tU3c5d3xvBjU4zXcaRqwewJNZdZjOCywFux/pKCQHs07e72mIFYleaIzG/7nf6N3iXFzbQcsCtBmyV43XQthCK6O2Aa0N4zKOt1XRQ8aB2FcZDqMXrcubDxLW46xNjo4HfrpTj6xfsj59FDFj1g+XHdVyX8O+CpJydvWH5NTn9e8RKJBgTGtRsaU916tUxYHtN2Vum3lDhEIjNSqRxqzC3hb1Qkv8iZvly60Bbi2Od/+GwjXw5N6dVuyB6J/ZXsml8kr/Bt0cQMgidvBGgtGdHVe1ArG4Z2geBXxwhsQmAapgFSwyvARCstOSZJU1qFiB+2pHiWiGZlmTKc0w4tOyQRI/2wppJQcXztX7H5DcP/1LBtDgH9Q4StAeoO3JWrvqT7al1arsFoHGUcDEpA+EGjFpMzArBdnrd0gcS1i1n2tr9RnkWCNXzifWlYYuIgvmc2sOcVWU+/IDI8S73CPND8OL2E3uKsGxqFBF0Zp0BLxbYWJxsYjhXG4SH2TMuG7aI4GKkJSbqCIgr7SDbEUfkkozFPtq8SGtjcoGOXG58QrjORjOtLZOPiY43jCPH8xVrtU8jVOOIY4B/U9mCabynO4sNvTjWWaUFndy5ueBXv4eltk1+IHcHHZUNvQAHoADpd2wqfEdDgxJ2XcH/BPwJlHeoAMZtIcC8Hl3s=
